### ISSUE TITLE
MVP リリース　レビュー依頼

### ISSUE THREAD

**Issue by johnny23ryo** [johnny23ryo/kodora-Co-Driver-#117]
お世話になっております。
卒業試験のMVPリリース依頼を提出いたします。
お忙しいところ恐れ入りますが、ご確認のほどよろしくお願い致します。

 ### **各種情報**

サービス名：コドラ(kodora-Co-Driver)
サービスURL：https://kodora-co-driver-2.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

**実装予定の機能**
- [ ] 新規登録
- [ ] ログイン
- [ ] プロフィール(マイページ)
- [ ] プロフィール編集(マイページ編集)
- [ ] Googleマップに投稿されたイベントをピンで表示
- [ ] 表示されたピンをクリックすると詳細表示
- [ ] 投稿機能
- [ ] 投稿詳細
- [ ] 投稿一覧
- [ ] 投稿編集
- [ ] google map api　を使用した2点間ルート案内機能
- [ ] openai api　を使用したおすすめの観光地、休憩所、食事処検索機能

**必要なページ**
- [ ] トップページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] マイページ
- [ ] マイページ編集
- [ ] おすすめのスポット一覧ページ
- [ ] おすすめのレストランページ
- [ ] おすすめの休憩所ページ
- [ ] おすすめの観光地ページ
- [ ] ルート検索ページ
- [ ] イベント一覧ページ
- [ ] イベント詳細ページ
- [ ] イベント編集ページ
- [ ] イベント投稿ページ

## READMEレビュー時から変更した機能
特にありません

##本リリース時に実装したい機能
- [ ]利用規約ページ
- [ ]プライバシーポリシーページ
- [ ]お問合せフォーム
- [ ]Google認証ログイン
- [ ]Xシェア機能
- [ ]マルチ検索,オートコンプリート機能
- [ ]独自ドメインの取得
- [ ]画像保存　インフラ
- [ ]パスワードリセットページ
- [ ]ルート保存機能
- 
## サービスイメージがわかるようなスクリーンショット等

管理画面等はございません。

トップページ画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 54 06" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/9090a264-769e-4896-a05a-df54ef5b1908">

おすすめのスポット一覧画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 54 17" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/6628bcab-e91a-4412-8045-114d95837106">

おすすめの食事処検索画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 54 41" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/bc7ff08f-b3ca-4a62-bcf3-95bb32f4d240">

おすすめの観光地検索画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 54 32" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/0e887857-9541-4e00-aa4a-820e7956de82">

おすすめの休憩所検索画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 54 59" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/2a398ade-0b6c-4e99-a494-d3939663141e">

イベント一覧画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 56 42" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/ad37e9b5-390b-4cf1-bedb-a03cf2fbe754">

イベント詳細画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 57 40" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/7a027648-e5c9-4ded-8ebe-51d6339407fb">

イベント編集画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 57 52" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/cd804398-428d-4f1a-a07e-8dbe7f65ce25">

イベント投稿画面
<img width="1674" alt="スクリーンショット 2024-06-19 19 09 54" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/b5b5f3f5-7bc2-43ac-9bb2-3feeb9b4d88c">

ルート検索画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 55 09" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/59110b87-9ff8-4b13-a766-e5f5c9338924">

マイページ画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 58 04" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/867ad203-d989-4e82-9a01-faa0a040f5e3">

マイページ編集画面
<img width="1674" alt="スクリーンショット 2024-06-19 18 58 12" src="https://github.com/johnny23ryo/kodora-Co-Driver-/assets/132822972/dbd263da-1c45-4831-9811-e82896d2b3fc">

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
