### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by johnny23ryo** [johnny23ryo/kodora-Co-Driver-#61]
###概要

###実装予定の機能

会員登録・ログイン
投稿一覧
投稿詳細
投稿機能
マイページ
ドライブ履歴の保存
ルート検索
Google認証機能
xシェア機能
おすすめスポット検索
保存したルート一覧
グーグルマップapiで行き先を検索した際にマップ上の道中にユーザーが投稿したイベントがピンで表示

#必要なページ
ホーム
サインアップ
ログイン
イベント一覧
イベント詳細
イベント投稿
ルート検索
おすすめのスポット一覧
おすすめの観光地検索
おすすめの食事処検索
おすすめの休憩所検索
マイページ
ルート保存

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

---

rails newのカードも作成しましょう。

外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、ストーリーポイント5以上を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5以上を付けているように見受けられました。
ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by johnny23ryo** [comment]
レビューありがとうございます。

外部APIや技術に関して調査するもののカードを用意しました。

また、ストーリーポイント5以上を付けているカードの機能を細分化し不透明な箇所の可視化を行いました。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
カード作成までできていますが、各カードがissueになっていないようなので対応をお願いいたします。

また、以下はコメントになります。

---

- デプロイはrails new 直後に行いましょう。
